version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  groups:
    quarkus:
      patterns:
      - "quarkus*"
      - "io.quarkus*"
  open-pull-requests-limit: 10
  reviewers:
  - mbarbero
